# Example configuration file for training a model
[model]
model = "FracBNNModel" # Select among any model available in the qnn/models directory
model_args = {name="FracBNN", in_channels=3, out_features=10, input_size=32, num_classes=10}

seed = 1408

[train]
epochs = 300
optimizer = "sgd" # Select among sgd, adam
loss_fn = "cross_entropy" # Select among cross_entropy, mse
optim_args = {lr=0.1, momentum=0.9, weight_decay=0.0001}
scheduler_args = {milestones = [150,245], gamma = 0.1}
device = "cuda"

[dataset]
dataset = "c10" # Select among c10, c100, mnist
batch_size = 128

[results]
explore = ["none"]
plots = ["accuracy", "loss", "weight_histogram"]