# Example configuration file for training a model
[model]
model = "FracBNNModel" # Select among any model available in the qnn/models directory
model_args = {name="FracBNN", in_channels=3, out_features=10, input_size=32, num_classes=10, thermometer=true}
seed = 1408

[train]
epochs = 600
optimizer = "adam" # Select among sgd, adam
loss_fn = "cross_entropy" # Select among cross_entropy, mse
optim_args = {lr=1e-3, betas=[0.9, 0.999], weight_decay=0.0}
scheduler = "MultiStepLR" # Select among MultiStepLR, BinMultiStepLR
scheduler_args = {milestones = [100,150,200], gamma = 0.1, fp_pretraining_end=300}
device = "cuda"
freeze_agent = "NullFreezer"
freeze_args = {name='no freeze'}
manual_freeze = false

[dataset]
dataset = "c10" # Select among c10, c100, mnist
batch_size = 128

[results]
explore = ["none"]
plots = ["accuracy", "loss", "weight_histogram"]