[model]
model = "VGG" # Select among any model available in the qnn/models directory
model_args = {name="VGG_full_binary", in_channels=3, out_features=10, binary_weights=true, binary_activations=true}
weights = "runs/results_config_0/weights/VGG_full_binary.pth" # Path to pre-trained weights, if any
seed = 1408

[train]
epochs = 200
optimizer = "adam" # Select among sgd, adam
loss_fn = "cross_entropy" # Select among cross_entropy, mse
optim_args = {lr=1e-3, betas=[0.9, 0.999], weight_decay=0.0}
scheduler = "MultiStepLR" # Select among MultiStepLR, BinMultiStepLR
scheduler_args = {milestones = [25,50,75], gamma = 0.1}
device = "cuda"
freeze_agent = "SignFrequencyGV"
freeze_args = {name='sign change frequency 1', warmup=0, start=10, low_freq=0.01, high_freq=0.99, momentum=0.9, prob=0.5}
manual_freeze = false

[dataset]
dataset = "c10" # Select among c10, c100, mnist
batch_size = 128

[results]
explore = ["none"]
plots = ["accuracy", "error_rate", "loss", "weight_histogram", "frozen"]