[model]
model = "VGG" # Select among any model available in the qnn/models directory
model_args = {name="VGG_full_binary", in_channels=3, out_features=10, binary_weights=true, binary_activations=true}
weights = "None" # Path to pre-trained weights, if any
seed = 1408

[train]
epochs = 300
optimizer = "adam" # Select among sgd, adam
loss_fn = "cross_entropy" # Select among cross_entropy, mse
optim_args = {lr=1e-3, betas=[0.9, 0.999], weight_decay=0.0}
scheduler = "MultiStepLR" # Select among MultiStepLR, BinMultiStepLR
scheduler_args = {milestones = [100,150,200], gamma = 0.1, fp_pretraining_end=310}
device = "cuda"
freeze_agent = "NoFreeze"
freeze_args = {name='no freeze'}
manual_freeze = false

[dataset]
dataset = "c10" # Select among c10, c100, mnist
batch_size = 128

[results]
explore = ["none"]
plots = ["accuracy", "error_rate", "loss", "weight_histogram", "frozen"]