[model]
model = "bVGG" # Select among AlexNet, mbv2, resnet18, resnet50, mcunet
dbits = 1 # Select the bit size of hidden layers data
weights = "scratch" # Select among pretrained, scratch
seed = 1408

[train]
epochs = 1000
optimizer = "sgd" # Select among sgd, adam
loss_fn = "cross_entropy" # Select among cross_entropy, mse
optim_args = {lr=0.1, momentum=0.9, weight_decay=0.0001}
scheduler_args = {milestones = [500,850], gamma = 0.1}
device = "cuda"
freeze_agent = "threshold"
freeze_args = {threshold=0.01, activation_time=100}

[dataset]
dataset = "c10" # Select among c10, c100, mnist
batch_size = 256

[measures]
measures = ["None"]